export {default as Home} from './home/Home';
export {default as About} from './about/About';
export {default as Serveces} from './serveces/Serveces';
export {default as EmployeDash} from './employeDashboard/EmployeDash';
export {default as AdminDashboard} from './AdminDashboard/AdminDashboard';
export {default as UserAdd} from './employeDashboard/DashComponents/UserAdd';
export {default as LoginForm} from './Login Form/LoginForm';
export {default as UpdateUser} from './employeDashboard/DashComponents/UpdateUser';
export {default as Loading} from './Loading/Loading';
export {default as Customer} from './Customer/Customer'
export {default as AdminRequireAuth} from './auth/AdminRequireAuth'
export {default as CreateUserAdmin} from './AdminDashboard/adminComponents/CreateUserAdmin'
export {default as EmployeeRequireAuth} from './auth/EmployeeRequireAuth'
export {default as EmpShow} from './AdminDashboard/adminComponents/EmpShow'
export {default as CurrencyRate} from './currencyRates/CurrencyRate'
export {default as CreateBranch} from './AdminDashboard/adminComponents/CreateBranch'
export {default as UpdateUserAdmin} from './AdminDashboard/adminComponents/UpdateUserAdmin'
export {default as CostumerShow} from './AdminDashboard/adminComponents/CostumerShow'
export {default as AllCustomer} from './employeDashboard/DashComponents/AllCustomer'
export {default as CreatAccount} from './employeDashboard/DashComponents/CreatAccount'
export {default as DepositMony} from './employeDashboard/DashComponents/DepositMony'
export {default as MonyTransfer} from './employeDashboard/DashComponents/MonyTransfer'
export {default as AccountManage} from './employeDashboard/DashComponents/AccountManage'
export {default as ShowBranches} from './employeDashboard/DashComponents/ShowBranches'
export {default as AccountsInfo} from './employeDashboard/DashComponents/AccountsInfo'
export {default as PersonelDetails} from '../components/Customer/PersonelDetails'
export {default as CustomerAccountInfo} from '../components/Customer/CustomerAccountInfo'
export {default as UpdateBranch} from '../components/AdminDashboard/adminComponents/UpdateBranch'
export {default as WithdrawMony} from '../components/employeDashboard/DashComponents/WidthdrawMony'
export {default as Transhistory} from '../components/employeDashboard/DashComponents/Transhistory'
export {default as Transfer} from './Customer/Transfer'
export {default as HTransaction} from './Customer/HTransaction'
export {default as CustomerRequireAuth} from './auth/CustomerRequireAuth'
export {default as RequireBack} from './auth/ReqeuireBack'
export {default as CantactUs} from './contactUs/CantactUs'